### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by MohsenNz** [awakesecurity/gRPC-haskell#161]
How can I use gRPC-Haskell in my-project?
It seems adding to cabal as build-depends doesn't work, because the version in Hackage is out of data (0.1.0).
Also, I tried to add master repo as dependency but still cabal build failed.

**Comment by riz0id** [comment]
You can use Nix or can pull the tip of the main repo and configure the correct dependencies in the cabal project file.

**Comment by MohsenNz** [comment]
I need an example of how to figure out the project with nix to use this library spacial in flake if possible.

**Comment by riz0id** [comment]
> I need an example of how to figure out the project with nix to use this library spacial in flake if possible.

If you're already familiar with Nix I encourage you to take a look at how Haskell packages are provisioned in `release.nix`.  The Haskell packages overlay in `release.nix` is used to compile the examples we provide in the `examples/` directory. Instantiating the derivation as a Nix flake will not require you to change anything.

Until I'm giving more information, I must assume that the issue you're having is unrelated to `grpc-rest`. If there is a particular problem with building the derivation, then you should provide more context about what the problem is, why you believe it is an issue, and ideally how that issue could be addressed by yourself, me, or other maintainers. Otherwise, I feel like there may be better places for you to seek assistance other than here.

Thanks

**Comment by MohsenNz** [comment]
OK, I added `grpc-haskell` as package to my nix development environment, as it had described in release.nix.
```bash
┌── dev/haskel-grpc-tutorial/arithmetic2 via λ 9.4.8 via ❄️   impure (ghc-shell-for-arithmetic-1.6-0-env)
λ
```
Now the HLS still can't find the module:
![Screenshot from 2024-03-14 00-56-24](https://github.com/awakesecurity/gRPC-haskell/assets/23291352/fc3e9b10-98aa-45c5-9c95-1e6a9e3efda7)
Should I add it to cabal too or something else ?
