### ISSUE TITLE
the grpc_call_destroy function has  removed in current grpc version 

### ISSUE THREAD

**Issue by mut0u** [awakesecurity/gRPC-haskell#48]
The grpc version is up to 1.91 and I found that grpc_call_destroy has been removed in the grpc.h file.
Do you have a plan to update the grpc version?  Or I have to use the grpc 1.0.1 version?

**Comment by ixmatus** [comment]
AFAIK we do not support GRPC 1.91 and I do not recommend using version 1.0.1 because version 1.2.0 is required. Newer versions of GRPC are untested in our builds and deployments.

I'm not sure when we will get around to upgrading the Haskell code to support a newer version of GRPC. We encourage and welcome pull requests though!

I'm closing this because we don't support versions of GRPC newer than 1.2.0.

**Comment by Gabriel439** [comment]
Note that there is another issue to upgrade to the `grpc` provided by Nixpkgs 17.09 in https://github.com/awakesecurity/gRPC-haskell/issues/44

I've been slowly chipping away at that and when that is done we should support `grpc-1.8.3.`
