### ISSUE TITLE
Put it on Hackage

### ISSUE THREAD

**Issue by ndmitchell** [awakesecurity/gRPC-haskell#65]
I couldn't figure out why these libraries aren't on Hackage/Stackage, but need installing from git?

**Comment by Gabriel439** [comment]
We're going to aim to push to Hackage at end of August.  We originally had some larger changes planned before pushing to Hackage but in response to your request we've decided to instead:

* Document our roadmap for planned changes so that we're more transparent about the development process
* Release to Hackage after a pass to polish up the current state of the library and iterate on that

**Comment by ndmitchell** [comment]
Thanks, that would be great!

**Comment by jkachmar** [comment]
Are there any updates on this?

(Sorry to bump the issue thread, it's just been a few months and I'm curious if Hackage/Stackage publication is still on some roadmap)

**Comment by Gabriel439** [comment]
@jkachmar: Sorry for the delay.  We're really behind on this as you can probably tell.  I'll do my best to address this before the holidays.

**Comment by gbaz** [comment]
Maybe we can revisit in the next few months?

**Comment by loewenstein** [comment]
Any update on this?

**Comment by theGhostJW** [comment]
Hey I just got to this repo from https://hackage.haskell.org/package/grpc-haskell

**Comment by Gabriel439** [comment]
Yeah, I just forgot to close this issue.  Thanks for the reminder! 🙂
